name = "Fir V1 Todo List"
description = ""
statuses = [
    { name = "todo", color = "light_magenta", order = 750, hide_by_default = false },
    { name = "hold", color = "red", order = 800, hide_by_default = false },
    { name = "prog", color = "light_blue", order = 600, hide_by_default = false },
    { name = "pr", color = "light_yellow", order = 550, hide_by_default = false },
    { name = "done", color = "light_green", order = 499, hide_by_default = true },
    { name = "rejected", color = "light_red", order = 850, hide_by_default = true },
    { name = "backlog", color = "light_cyan", order = 900, hide_by_default = true },
]

[config]
"status.default" = "todo"
"enable.ls.hide_done_tasks" = "1"
"enable.column.link" = "0"
"enable.column.assigned" = "1"

[[tasks]]
id = "FpB5CDGv"
name = "Toml for config"
tags = []
status = "done"
added = "2023-12-01"
modified = "2023-12-02 12:53:19"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "LHV2ya5S"
name = "Tags"
tags = []
status = "done"
added = "2023-12-01"
modified = "2023-12-01"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "j5ZXVUWv"
name = "Date improvements"
tags = []
status = "done"
added = "2023-12-01"
modified = "2023-12-01"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "ipmuAEKb"
name = "Marshmellow for object mapping"
tags = []
status = "done"
added = "2023-12-01"
modified = "2023-12-02 12:45:48"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "KXeUk7EH"
name = "Profiles should have their own files"
tags = []
status = "done"
added = "2023-12-01"
modified = "2023-12-02 15:23:00"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "KHyxz4d9"
name = "Local & global directories for profiles"
tags = []
status = "done"
added = "2023-12-01"
modified = "2023-12-02 15:25:49"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "NeqTwGNv"
name = "Print info after create/modify"
tags = []
status = "done"
added = "2023-12-01"
modified = "2023-12-02 12:45:33"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "CCnnMuCN"
name = "Fix commands for config and profile"
tags = [
    "helloworld!",
]
status = "done"
added = "2023-12-02 00:12:41"
modified = "2023-12-02 12:48:11"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "WcYJ8odS"
name = "Finish status type checking when setting values"
tags = []
status = "done"
added = "2023-12-02 12:48:39"
modified = "2023-12-02 15:28:33"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "edJYyRfi"
name = "Add easier way to set status"
tags = []
status = "done"
added = "2023-12-02 12:48:52"
modified = "2023-12-02 12:48:52"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "PojCndkn"
name = "Order task list by status todo -> doing -> done"
tags = []
status = "done"
added = "2023-12-02 12:49:26"
modified = "2023-12-02 13:03:45"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "hwhqJFuh"
name = "Create profiles (and a default)"
tags = []
status = "done"
added = "2023-12-02 12:50:32"
modified = "2023-12-02 12:50:32"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "4UVqtcZf"
name = "Tidy private methods in data repos"
tags = [
    "complexity:med",
]
status = "todo"
added = "2023-12-02 13:05:16"
modified = "2023-12-05 20:39:48"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "FNtWLSZ3"
name = "Review error handling"
tags = [
    "complexity:high",
]
status = "hold"
added = "2023-12-02 13:09:13"
modified = "2023-12-02 13:09:13"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "2sk6kn3f"
name = "Add description, assigned, notes, link fields"
tags = [
    "complexity:low",
]
status = "done"
added = "2023-12-02 15:16:02"
modified = "2023-12-02 15:16:02"
due = ""
link = "https://github.com/weavc/fir/issues/1"
description = "We need to be able to add descriptions, links and assign people to tasks. Without these features the software is quite bare."
priority = 999
assigned_to = [
    "chris",
    "john",
]

[[tasks]]
id = "iRsRTrWN"
name = "Enable config options (enable table columns etc)"
tags = []
status = "done"
added = "2023-12-02 15:18:03"
modified = "2023-12-02 15:18:03"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "U6kKMjVJ"
name = "ConfigOption to hide done tasks from fir ls"
tags = []
status = "done"
added = "2023-12-02 15:19:01"
modified = "2023-12-02 15:19:50"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "KsdLSbTT"
name = "Better commands to add and remove tags"
tags = []
status = "done"
added = "2023-12-02 17:13:05"
modified = "2023-12-02 17:13:05"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "inbcjR3B"
name = "Better help commands"
tags = []
status = "done"
added = "2023-12-02 17:22:43"
modified = "2023-12-02 17:22:43"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "SFqYA3ZT"
name = "Add new task properties to new and mod commands"
tags = []
status = "done"
added = "2023-12-02 20:03:16"
modified = "2023-12-02 20:03:16"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "YW2rcJgB"
name = "Add a forth status category for on hold tasks"
tags = [
    "complextity:med",
    "feature",
]
status = "done"
added = "2023-12-02 20:57:45"
modified = "2023-12-05 20:32:14"
due = ""
link = ""
description = "On hold tasks don't fit into the current categories, so we should add another"
priority = 1
assigned_to = [
    "Chris",
]

[[tasks]]
id = "a35aob8f"
name = "Easier to use ids"
tags = []
status = "done"
added = "2023-12-03 11:01:42"
modified = "2023-12-03 11:01:42"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "emscsy6y"
name = "Better autocomplete"
tags = []
status = "todo"
added = "2023-12-03 12:04:46"
modified = "2023-12-03 12:04:46"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "eayc6rhs"
name = "Work on default commands"
tags = []
status = "done"
added = "2023-12-03 12:10:16"
modified = "2023-12-03 12:10:16"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "2vgdclb6"
name = "Register parser/sub parser to the command / handler so we can print help"
tags = []
status = "todo"
added = "2023-12-03 21:56:02"
modified = "2023-12-03 21:56:02"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "3i01rnha"
name = "Fix description when setting from new, appears as array"
tags = []
status = "done"
added = "2023-12-03 22:10:36"
modified = "2023-12-03 22:10:36"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "ebmuxx2i"
name = "Order by status within status categories"
tags = []
status = "done"
added = "2023-12-04 15:59:47"
modified = "2023-12-04 15:59:47"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "4fduau21"
name = "Filter ls by tag & assigned"
tags = []
status = "done"
added = "2023-12-04 16:00:22"
modified = "2023-12-04 16:00:22"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "9zz1aa06"
name = "Truncate names (+ config option)"
tags = []
status = "done"
added = "2023-12-04 16:00:46"
modified = "2023-12-04 16:00:46"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "af9e146n"
name = "Use name from toml file when linking"
tags = []
status = "todo"
added = "2023-12-04 16:01:49"
modified = "2023-12-04 16:01:49"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "6ck8pcn9"
name = "Bug requiring a profile_path value when creating new"
tags = []
status = "done"
added = "2023-12-04 16:02:13"
modified = "2023-12-04 16:02:13"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "4tlonk56"
name = "Add speech marks around values in print"
tags = []
status = "done"
added = "2023-12-04 16:05:14"
modified = "2023-12-04 16:05:14"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "2cob2gk8"
name = "Allow name value instead of id?"
tags = []
status = "rejected"
added = "2023-12-04 16:06:04"
modified = "2023-12-04 16:06:04"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "bsgvhrsc"
name = "If theres multiple matches on an id, error"
tags = []
status = "todo"
added = "2023-12-04 16:06:51"
modified = "2023-12-04 16:06:51"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "2y7lcaa9"
name = "Reassign task with a new id"
tags = []
status = "hold"
added = "2023-12-04 16:07:27"
modified = "2023-12-04 16:07:27"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "auq7vjrd"
name = "Headers optional param on ls"
tags = []
status = "todo"
added = "2023-12-05 21:50:09"
modified = "2023-12-05 21:50:09"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []
