name = "fir.future"
description = ""
statuses = [
    { name = "done", color = "light_blue", order = 400, hide_by_default = true },
    { name = "maybe", color = "light_yellow", order = 500, hide_by_default = false },
    { name = "yes", color = "light_green", order = 550, hide_by_default = false },
    { name = "no", color = "red", order = 850, hide_by_default = true },
]

[config]
"status.default" = "maybe"
"enable.log_task_post_modify" = "0"
"enable.column.due" = "0"
"enable.column.tags" = "0"
"enable.column.link" = "0"
"enable.column.description" = "0"
"enable.column.assigned" = "0"
"enable.column.priority" = "0"

[[tasks]]
id = "0n0jz7z3"
name = "'fir-serve', web client"
tags = []
status = "maybe"
added = "2023-12-03 22:02:19"
modified = "2023-12-03 22:02:19"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "f1xscrhp"
name = "'fir-cmd-builder', package up builder project"
tags = []
status = "no"
added = "2023-12-03 22:05:41"
modified = "2023-12-03 22:05:41"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "d3ra7b8b"
name = "Add backlog feature"
tags = []
status = "done"
added = "2023-12-03 22:06:38"
modified = "2023-12-03 22:06:38"
due = ""
link = ""
description = "['Backlog of tasks that dont show on regular task list but can easily be moved into the task list']"
priority = 100
assigned_to = []

[[tasks]]
id = "dbudvny3"
name = "Tracking dates for when work started & finished"
tags = []
status = "yes"
added = "2023-12-03 22:11:25"
modified = "2023-12-03 22:11:25"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "0ezroiwd"
name = "Forth status for on hold"
tags = []
status = "done"
added = "2023-12-03 22:15:33"
modified = "2023-12-03 22:15:33"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "baq67i9j"
name = "Git integration using GitPython"
tags = []
status = "maybe"
added = "2023-12-04 16:03:00"
modified = "2023-12-04 16:03:00"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "1udvacyl"
name = "Macros for ls"
tags = []
status = "maybe"
added = "2023-12-05 21:55:52"
modified = "2023-12-05 21:55:52"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []
