name = "Fir V1 Todo List"
description = ""

[config]
"status.default" = "TODO"
"status.todo" = "TODO,ONHOLD"
"status.doing" = "PROG,PR"
"status.done" = "DONE,REJECTED"
"enable.ls.hide_done_tasks" = "1"

[[tasks]]
id = "FpB5CDGv"
name = "Toml for config"
tags = [
    "assigned:andrew,jordan",
]
status = "DONE"
added = "2023-12-01"
modified = "2023-12-02 12:53:19"
due = ""

[[tasks]]
id = "LHV2ya5S"
name = "Tags"
tags = []
status = "DONE"
added = "2023-12-01"
modified = "2023-12-01"
due = ""

[[tasks]]
id = "j5ZXVUWv"
name = "Date improvements"
tags = []
status = "DONE"
added = "2023-12-01"
modified = "2023-12-01"
due = ""

[[tasks]]
id = "ipmuAEKb"
name = "Marshmellow for object mapping"
tags = []
status = "DONE"
added = "2023-12-01"
modified = "2023-12-02 12:45:48"
due = ""

[[tasks]]
id = "KXeUk7EH"
name = "Profiles should have their own files"
tags = []
status = "DONE"
added = "2023-12-01"
modified = "2023-12-02 15:23:00"
due = ""

[[tasks]]
id = "KHyxz4d9"
name = "Local & global directories for profiles"
tags = []
status = "DONE"
added = "2023-12-01"
modified = "2023-12-02 15:25:49"
due = ""

[[tasks]]
id = "NeqTwGNv"
name = "Print info after create/modify"
tags = []
status = "DONE"
added = "2023-12-01"
modified = "2023-12-02 12:45:33"
due = ""

[[tasks]]
id = "CCnnMuCN"
name = "Fix commands for config and profile"
tags = [
    "helloworld!",
]
status = "PROG"
added = "2023-12-02 00:12:41"
modified = "2023-12-02 12:48:11"
due = ""

[[tasks]]
id = "WcYJ8odS"
name = "Finish status type checking when setting values"
tags = []
status = "DONE"
added = "2023-12-02 12:48:39"
modified = "2023-12-02 15:28:33"
due = ""

[[tasks]]
id = "edJYyRfi"
name = "Add easier way to set status"
tags = []
status = "DONE"
added = "2023-12-02 12:48:52"
modified = "2023-12-02 12:48:52"
due = ""

[[tasks]]
id = "PojCndkn"
name = "Order task list by status todo -> doing -> done"
tags = []
status = "DONE"
added = "2023-12-02 12:49:26"
modified = "2023-12-02 13:03:45"
due = ""

[[tasks]]
id = "hwhqJFuh"
name = "Create profiles (and a default)"
tags = []
status = "DONE"
added = "2023-12-02 12:50:32"
modified = "2023-12-02 12:50:32"
due = ""

[[tasks]]
id = "4UVqtcZf"
name = "Tidy private methods in data repos"
tags = []
status = "TODO"
added = "2023-12-02 13:05:16"
modified = "2023-12-02 13:05:16"
due = ""

[[tasks]]
id = "FNtWLSZ3"
name = "Review error handling"
tags = []
status = "TODO"
added = "2023-12-02 13:09:13"
modified = "2023-12-02 13:09:13"
due = ""

[[tasks]]
id = "2sk6kn3f"
name = "Add description, assigned, notes, link fields"
tags = []
status = "TODO"
added = "2023-12-02 15:16:02"
modified = "2023-12-02 15:16:02"
due = ""

[[tasks]]
id = "iRsRTrWN"
name = "Enable config options (enable table columns etc)"
tags = []
status = "PROG"
added = "2023-12-02 15:18:03"
modified = "2023-12-02 15:18:03"
due = ""

[[tasks]]
id = "U6kKMjVJ"
name = "ConfigOption to hide done tasks from fir ls"
tags = []
status = "DONE"
added = "2023-12-02 15:19:01"
modified = "2023-12-02 15:19:50"
due = ""

[[tasks]]
id = "KsdLSbTT"
name = "Better commands to add and remove tags"
tags = []
status = "DONE"
added = "2023-12-02 17:13:05"
modified = "2023-12-02 17:13:05"
due = ""
