name = "Fir V1 Todo List"
description = ""

[config]
"status.default" = "TODO"
"status.todo" = "TODO,HOLD"
"status.doing" = "PROG,PR"
"status.done" = "DONE,REJECTED"
"enable.ls.hide_done_tasks" = "1"
"enable.column.link" = "0"
"enable.column.assigned" = "1"

[[tasks]]
id = "FpB5CDGv"
name = "Toml for config"
tags = []
status = "DONE"
added = "2023-12-01"
modified = "2023-12-02 12:53:19"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "LHV2ya5S"
name = "Tags"
tags = []
status = "DONE"
added = "2023-12-01"
modified = "2023-12-01"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "j5ZXVUWv"
name = "Date improvements"
tags = []
status = "DONE"
added = "2023-12-01"
modified = "2023-12-01"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "ipmuAEKb"
name = "Marshmellow for object mapping"
tags = []
status = "DONE"
added = "2023-12-01"
modified = "2023-12-02 12:45:48"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "KXeUk7EH"
name = "Profiles should have their own files"
tags = []
status = "DONE"
added = "2023-12-01"
modified = "2023-12-02 15:23:00"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "KHyxz4d9"
name = "Local & global directories for profiles"
tags = []
status = "DONE"
added = "2023-12-01"
modified = "2023-12-02 15:25:49"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "NeqTwGNv"
name = "Print info after create/modify"
tags = []
status = "DONE"
added = "2023-12-01"
modified = "2023-12-02 12:45:33"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "CCnnMuCN"
name = "Fix commands for config and profile"
tags = [
    "helloworld!",
]
status = "DONE"
added = "2023-12-02 00:12:41"
modified = "2023-12-02 12:48:11"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "WcYJ8odS"
name = "Finish status type checking when setting values"
tags = []
status = "DONE"
added = "2023-12-02 12:48:39"
modified = "2023-12-02 15:28:33"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "edJYyRfi"
name = "Add easier way to set status"
tags = []
status = "DONE"
added = "2023-12-02 12:48:52"
modified = "2023-12-02 12:48:52"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "PojCndkn"
name = "Order task list by status todo -> doing -> done"
tags = []
status = "DONE"
added = "2023-12-02 12:49:26"
modified = "2023-12-02 13:03:45"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "hwhqJFuh"
name = "Create profiles (and a default)"
tags = []
status = "DONE"
added = "2023-12-02 12:50:32"
modified = "2023-12-02 12:50:32"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "4UVqtcZf"
name = "Tidy private methods in data repos"
tags = [
    "complexity:med",
]
status = "PR"
added = "2023-12-02 13:05:16"
modified = "2023-12-02 13:05:16"
due = ""
link = ""
description = ""
priority = 100
assigned_to = [
    "Chris",
]

[[tasks]]
id = "FNtWLSZ3"
name = "Review error handling"
tags = [
    "complexity:high",
]
status = "PROG"
added = "2023-12-02 13:09:13"
modified = "2023-12-02 13:09:13"
due = ""
link = ""
description = ""
priority = 100
assigned_to = [
    "Chris",
    "Megan",
]

[[tasks]]
id = "2sk6kn3f"
name = "Add description, assigned, notes, link fields"
tags = [
    "complexity:low",
]
status = "DONE"
added = "2023-12-02 15:16:02"
modified = "2023-12-02 15:16:02"
due = ""
link = "https://github.com/weavc/fir/issues/1"
description = "We need to be able to add descriptions, links and assign people to tasks. Without these features the software is quite bare."
priority = 999
assigned_to = [
    "chris",
    "john",
]

[[tasks]]
id = "iRsRTrWN"
name = "Enable config options (enable table columns etc)"
tags = []
status = "DONE"
added = "2023-12-02 15:18:03"
modified = "2023-12-02 15:18:03"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "U6kKMjVJ"
name = "ConfigOption to hide done tasks from fir ls"
tags = []
status = "DONE"
added = "2023-12-02 15:19:01"
modified = "2023-12-02 15:19:50"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "KsdLSbTT"
name = "Better commands to add and remove tags"
tags = []
status = "DONE"
added = "2023-12-02 17:13:05"
modified = "2023-12-02 17:13:05"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "inbcjR3B"
name = "Better help commands"
tags = []
status = "HOLD"
added = "2023-12-02 17:22:43"
modified = "2023-12-02 17:22:43"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "SFqYA3ZT"
name = "Add new task properties to new and mod commands"
tags = []
status = "DONE"
added = "2023-12-02 20:03:16"
modified = "2023-12-02 20:03:16"
due = ""
link = ""
description = ""
priority = 100
assigned_to = []

[[tasks]]
id = "kioPjfuk"
name = "Add a forth status category for on hold"
tags = [
    "feature",
    "complexity:med",
]
status = "TODO"
added = "2023-12-02 20:44:46"
modified = "2023-12-02 20:44:46"
due = ""
link = ""
description = "Tasks that are on hold don't really have a place within the current categories so we should create a new category group for it."
priority = 1
assigned_to = [
    "Chris",
]

[[tasks]]
id = "YW2rcJgB"
name = "Add a forth status category for on hold tasks"
tags = [
    "complextity:med",
    "feature",
]
status = "TODO"
added = "2023-12-02 20:57:45"
modified = "2023-12-02 20:57:45"
due = ""
link = ""
description = "On hold tasks don't fit into the current categories, so we should add another"
priority = 1
assigned_to = [
    "Chris",
]
